#!/usr/bin/env python
"""
Prepare HTML files for Flask-based serving.

This script reorganizes HTML files generated by XPCS webplot for optimal
Flask-based serving. It removes legacy static HTML files and optionally
organizes result directories into a subfolder structure.
"""

import os
import shutil
import argparse
import logging

logger = logging.getLogger(__name__)


def migrate_html_structure(html_folder='html', create_results_subfolder=False):
    """
    Migrate HTML folder structure from static to Flask-compatible format.

    Removes old static HTML files and optionally reorganizes result directories
    into a subfolder structure for better organization with Flask serving.

    Parameters
    ----------
    html_folder : str, optional
        Path to the HTML folder to migrate. Default is 'html'.
    create_results_subfolder : bool, optional
        If True, move result directories to a 'results' subfolder.
        If False, keep results in the root HTML folder. Default is False.

    Returns
    -------
    bool
        True if migration was successful, False if HTML folder doesn't exist.

    Notes
    -----
    The function performs the following operations:
    1. Removes old static files:
       - index.html, preview.html, iframe.html
       - jquery.minipreview.css, jquery.minipreview.js
    2. If create_results_subfolder is True:
       - Creates a 'results' subfolder
       - Moves all result directories (identified by metadata.json) to subfolder
    3. Cleans up any remaining HTML files in the root

    After migration, use the Flask server to view results:
    - Without subfolder: xpcs_webplot_server --html-folder html
    - With subfolder: xpcs_webplot_server --html-folder html/results

    See Also
    --------
    run_flask_server : Start Flask server to view migrated results

    Examples
    --------
    Migrate without creating subfolder:
    >>> migrate_html_structure('output')
    True
    
    Migrate and organize into subfolder:
    >>> migrate_html_structure('output', create_results_subfolder=True)
    True
    """
    if not os.path.exists(html_folder):
        logger.error(f"HTML folder '{html_folder}' does not exist")
        return False
    
    # Files to remove (old static index files)
    static_files_to_remove = ['index.html', 'preview.html', 'iframe.html', 
                              'jquery.minipreview.css', 'jquery.minipreview.js']
    
    # Remove old static files
    for filename in static_files_to_remove:
        filepath = os.path.join(html_folder, filename)
        if os.path.exists(filepath):
            os.remove(filepath)
            logger.info(f"Removed old static file: {filename}")
    
    if create_results_subfolder:
        # Create results subfolder
        results_folder = os.path.join(html_folder, 'results')
        if not os.path.exists(results_folder):
            os.makedirs(results_folder)
            logger.info(f"Created results subfolder: {results_folder}")
        
        # Move all result directories to the results subfolder
        items = os.listdir(html_folder)
        moved_count = 0
        
        for item in items:
            item_path = os.path.join(html_folder, item)
            
            # Skip if not a directory or if it's the results folder itself
            if not os.path.isdir(item_path) or item == 'results':
                continue
            
            # Check if it's a result directory (contains metadata.json)
            if os.path.exists(os.path.join(item_path, 'metadata.json')):
                new_path = os.path.join(results_folder, item)
                shutil.move(item_path, new_path)
                logger.info(f"Moved {item} to results subfolder")
                moved_count += 1
        
        logger.info(f"Moved {moved_count} result directories to results subfolder")
        
        # Update Flask app config if results are in subfolder
        logger.info("Note: When running the Flask server with results in a subfolder,")
        logger.info("      use: xpcs_webplot_server --html-folder html/results")
    
    # Clean up any remaining HTML files in the root
    for item in os.listdir(html_folder):
        if item.endswith('.html') and item not in ['index.html']:
            filepath = os.path.join(html_folder, item)
            os.remove(filepath)
            logger.info(f"Removed old HTML file: {item}")
    
    logger.info("Migration completed successfully!")
    logger.info("\nTo run the Flask server:")
    if create_results_subfolder:
        logger.info(f"  xpcs_webplot_server --html-folder {html_folder}/results")
    else:
        logger.info(f"  xpcs_webplot_server --html-folder {html_folder}")
    
    return True


def main():
    """
    Main entry point for the HTML preparation script.

    Parses command-line arguments and prepares the HTML structure
    to make XPCS webplot results compatible with Flask-based serving.

    Returns
    -------
    None
        Exits with code 1 if migration fails.

    Notes
    -----
    Command-line arguments:
    --html-folder : Path to HTML folder to migrate (default: 'html')
    --create-subfolder : Move result directories to 'results' subfolder
    --verbose, -v : Enable verbose logging output

    See Also
    --------
    migrate_html_structure : The underlying migration function

    Examples
    --------
    Basic preparation:
    $ python prepare_html_for_serving.py --html-folder output
    
    Preparation with subfolder organization:
    $ python prepare_html_for_serving.py --html-folder output --create-subfolder
    
    Verbose output:
    $ python prepare_html_for_serving.py --html-folder output --verbose
    """
    parser = argparse.ArgumentParser(
        description='Prepare XPCS WebPlot HTML structure for Flask-based serving')
    parser.add_argument('--html-folder', default='html',
                        help='Path to the HTML folder to prepare (default: html)')
    parser.add_argument('--create-subfolder', action='store_true',
                        help='Move result directories to a "results" subfolder')
    parser.add_argument('--verbose', '-v', action='store_true',
                        help='Enable verbose logging')
    
    args = parser.parse_args()
    
    # Configure logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(level=log_level, format='%(levelname)s: %(message)s')
    
    # Run migration
    success = migrate_html_structure(args.html_folder, args.create_subfolder)
    
    if not success:
        exit(1)


if __name__ == '__main__':
    main()
